# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

# Platform.
platform: x64

clone_folder: c:\gopath\src\github.com\minio\minio

# Environment variables
environment:
  GOVERSION: 1.8.3
  GOPATH: c:\gopath

# scripts that run after cloning repository
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%

# To run your custom scripts instead of automatic MSBuild
build_script:
  # Compile
  # We need to disable firewall - https://github.com/appveyor/ci/issues/1579#issuecomment-309830648
  - ps: Disable-NetFirewallRule -DisplayName 'File and Printer Sharing (SMB-Out)'
  - appveyor AddCompilationMessage "Starting Compile"
  - appveyor AddCompilationMessage "Compile Success"

# To run your custom scripts instead of automatic tests
test_script:
  # Unit tests
  - ps: Add-AppveyorTest "Unit Tests" -Outcome Running
  - cd cmd
  - go test -v
  - ps: Update-AppveyorTest "Unit Tests" -Outcome Passed

# to disable deployment
deploy: off
